dist: trusty
sudo: false
language: generic
services:
  - docker

script:
  - travis_wait 60 bin/ci
notifications:
  slack:
    secure: gBSJZTZoWP9dL+m2NVXsooqE/6qwZ3XvtPafSlcY1xwgzA3lEtfDIEB76dZd+2wLFO56v25us1L4EfUx1FCqHzXWD0W4Ve8ozBYBPdIJQy0531JL5YVPdFfd6ChKOIs0AyDmDB+AGM/4vbBvF9tCqNozdQfeO7D/mvPop1HgdF9TusFdmkqXG5pC0iDQHCeAkOc4VlHOSORvOLKTMGOBTdO0CS89a97vKIf+v50St+lIqQeANiSCdemcu4A8VXCmggGrMHim5NqyUCBMf8y691Y3E8Xsi6w4stzen3zecdRK4FU27/TMP++rK+NQlZ0VjbekoKliD9GMoyp8qNqZc9ukkWbwjo2tb/3G3Zp4Qr/zcX+qEQr2SEgFhjPAan8AdhmQo2mb9PjHg+9BC1NZJtwWRsUfhIccFGwKCepsDEZsOdclqhm4kdC8inPD1QUTd7y3u+bSSLh1t2zD5KahJQLuB3vh5RVbtLRNryYIe4wO/voxxV7i1+JkQ4GmySOpOwGTGNr+7vqDcAUgJFuwjpTrlw8xFceNX0vUOrt86hhOHLZvCone0aipfjjIaXj5T4HAFKGIglAhkQM5QVIbdIwmK997bz1UgJ+q64Lz31uxEpKO878E5SJV7Z2OdTr2U/VAet7RcMxbZZh5nTYZwEhSO18Q7Xi8bjjGIduU1P8=
